---
- name: make a dummy connection
  shell: /usr/bin/mongo --quiet --eval "{{ cmd }}"
  vars:
    cmd: "rs.isMaster().primary"
  changed_when: False
  check_mode: false

- name: try to get mongo master
  shell: /usr/bin/mongo --quiet --eval "{{ cmd }}" | cut -d":" -f1
  vars:
    cmd: "rs.isMaster().primary"
  register: mongo_master_out
  changed_when: False
  check_mode: false

- name: try to set mongo_master fact
  set_fact: mongo_master={{ mongo_master_out.stdout }}
  when: mongo_master_out|success and mongo_master_out.stdout != ""

- name: use init node as mongo_master as fallback
  set_fact: mongo_master={{ hostvars[mongo_init_node_name]['mongo_node_name'] }}
  when: mongo_master is not defined

- name: Print 'mongo_master' per node
  debug:
    msg: "{{ inventory_hostname }} -> {{ mongo_master }}"
