---
- name: Use 'mongo_init_node_name' as 'mongo_backup_source' if not defined
  set_fact: mongo_backup_source={{ mongo_init_node_name }}
  when: mongo_backup_source is not defined

- name: Configure Backup
  block:
  - name: create folder for backup script
    file: path=/opt/automongobackup owner=root group=root state=directory

  - name: create backup destination
    file: path={{ mongo_backup_destination }} owner=root group=root state=directory

  - name: render backup script
    template: src=automongobackup.sh.j2 dest=/opt/automongobackup/automongobackup.sh mode=0700

  - name: Create entry in /etc/cron.d
    cron:
      name: "Backup MongoDB"
      job: /opt/automongobackup/automongobackup.sh
      cron_file: automongobackup
      day: "{{ mongo_backup_cron.day }}"
      hour: "{{ mongo_backup_cron.hour }}"
      minute: "{{ mongo_backup_cron.minute }}"
  when: mongo_backup_node is defined and mongo_backup_node
